version: '3.2'

services:
  installer:
    image: yeticraft/installer:latest
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /etc/docker:/host/etc/docker
  
      # for dev purposes only
      - ${PWD}:/work
    #deploy:
    #  mode: global
    #  placement:
    #    constraints: [node.platform.os == linux]
